language: python
python: "3.6"

script:
  - pelican content -s publishconf.py

deploy:
  provider: pages
  api_key: $GH_TOKEN
  target-branch: gh-pages
  file_glob: true
  file: output/*
  skip_cleanup: true
  repo: happypet-app/www.happypet.app
